"""
Example 5.4: Off-policy Estimation of a Blackjack State Value We applied
both ordinary and weighted importance-sampling methods to estimate the value of a single
blackjack state (Example 5.1) from off-policy data. Recall that one of the advantages
of Monte Carlo methods is that they can be used to evaluate a single state without
forming estimates for any other states.

In this example, we evaluated the state in which
the dealer is showing a deuce, the sum of the player's cards is 13, and the player has
a usable ace (that is, the player holds an ace and a deuce, or equivalently three aces).
The data was generated by starting in this state then choosing to hit or stick at random
with equal probability (the behavior policy). The target policy was to stick only on
a sum of 20 or 21, as in Example 5.1. The value of this state under the target policy
is approximately -0.27726 (this was determined by separately generating one-hundred
million episodes using the target policy and averaging their returns). Both off-policy
methods closely approximated this value after 1000 off-policy episodes using the random
policy. To make sure they did this reliably, we performed 100 independent runs, each
starting from estimates of zero and learning for 10,000 episodes. Figure 5.3 shows the
resultant learning curves—the squared error of the estimates of each method as a function
of number of episodes, averaged over the 100 runs. The error approaches zero for both
algorithms, but the weighted importance-sampling method has much lower error at the
beginning, as is typical in practice.
"""

"""
- Generate V_mu, the behaviour policy
- Estimate V_pi, the target policy based on trajectories following mu
"""
from collections import defaultdict, Counter
import math
import multiprocessing as mp
from concurrent.futures import ProcessPoolExecutor
from typing import cast, override
import gymnasium as gym
from gymnasium.envs.toy_text.blackjack import BlackjackEnv, draw_card

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.figure import Figure
from tqdm import tqdm

from model_free.blackjack.agents.agent import HIT, STICK, BlackJackActT, BlackJackObsT, BlackJackPolicyT, MC_ES_BlackjackAgent

class ImportanceSampling_BlackjackAgent(MC_ES_BlackjackAgent):
    """
    The behaviour policy
    """
    def __init__(self, env: BlackjackEnv, gamma: float, pi: BlackJackPolicyT, fixed_pi: bool=True):
        super().__init__(env, gamma, pi, fixed_pi=fixed_pi)
        self.env = env

    @classmethod
    def make_random_policy(cls) -> BlackJackPolicyT:
        return cls.make_universal_policy(hit=0.5, stick=0.5)

    @classmethod
    def make_universal_policy(cls, hit: float, stick: float) -> BlackJackPolicyT:
        assert math.isclose(hit + stick, 1.0), "Probabilities must sum to 1"
        policy = {}
        for player_sum in range(12, 22):
            for dealer_show in range(1, 11):
                for usable_ace in [True, False]:
                    obs = (player_sum, dealer_show, usable_ace)
                    policy[obs] = {HIT: hit, STICK: stick}
        return policy

    @override
    def get_action(self, state: BlackJackObsT) -> BlackJackActT:
        action_probs = self.pi[state]
        actions, probs = zip(*action_probs.items())
        return np.random.choice(actions, p=probs)

    def init_env(self) -> None:
        self.env.reset()
        bj: BlackjackEnv = cast(BlackjackEnv, self.env.unwrapped)

        # force player to have usable ace + 2 -> sum 13
        bj.player = [1, 2]

        # sample dealer's hidden card according to the env's distribution
        hidden = draw_card(bj.np_random)
        bj.dealer = [2, hidden]

        # player, dealer, ace = bj._get_obs()
        # return player, dealer, bool(ace)

    @override
    def generate_episode(self) -> list[tuple[BlackJackObsT, BlackJackActT, float]]:
        history = []
        self.init_env()

        obs = self.env._get_obs()

        done = False
        while not done:
            action = self.get_action(obs)
            next_obs, reward, terminated, truncated, info = self.env.step(action)

            history.append((obs, action, float(reward)))

            done = terminated or truncated
            obs = next_obs

        return history

    def ordinary_IS(self,
                    mu_trajectories: list[list[tuple[BlackJackObsT, BlackJackActT, float]]],
                    mu_policy: BlackJackPolicyT,
                    checkpoints: list[int],
                    eval_states: list[BlackJackObsT]) -> dict[BlackJackObsT, list[float]]:
        """
        "It is convenient here to number time steps in a way that increases across episode boundaries.
        This enables us to use time-step numbers to refer to particular steps in particular episodes.
        In particular, we can define the set of all time steps in which state s is visited, denoted Tee(s).

        Also, let T(t) denote the first time of termination following time t, and G_t denote the return
        after t up through T(t). Then {G_t}_{t in T(s)} are the returns that pertain to state s, and
        {rho t:T(t)-1|}_{t in T(s)} are the corresponding importance-sampling ratios. To estimate v_pi(s),
        we simply scale the returns by the ratios and average the results.

        Every visit method.
        Need: Trajectories.
        Generate rho on the fly:
            product [k=t to T-1] pi(A_k|S_k)/mu(A_k|S_k)

        V(s) = sum [t in Tee(s)] rho_t:T(t)-1 G_t / |Tee(s)|
        """
        value_estimates: dict[BlackJackObsT, float] = defaultdict(float)
        visits: dict[BlackJackObsT, int] = Counter()

        result = {obs: [] for obs in eval_states}

        for idx, trajectory in enumerate(mu_trajectories, start=1):
            ratio = 1
            G = 0
            for (obs, act, reward) in trajectory[::-1]:
                ratio *= self.pi[obs][act] / mu_policy[obs][act]
                G = G * self.gamma + reward

                if obs in eval_states:
                    visits[obs] += 1
                    value_estimates[obs] += G * ratio

            if idx in checkpoints:
                for obs in eval_states:
                    if visits[obs] > 0:
                        result[obs].append(value_estimates[obs] / visits[obs])
                    else:
                        result[obs].append(0.0)

        return result

    def weighted_IS(self,
                    mu_trajectories: list[list[tuple[BlackJackObsT, BlackJackActT, float]]],
                    mu_policy: BlackJackPolicyT,
                    checkpoints: list[int],
                    eval_states: list[BlackJackObsT]) -> dict[BlackJackObsT, list[float]]:
        """
        "It is convenient here to number time steps in a way that increases across episode boundaries.
        This enables us to use time-step numbers to refer to particular steps in particular episodes.
        In particular, we can define the set of all time steps in which state s is visited, denoted Tee(s).

        Also, let T(t) denote the first time of termination following time t, and G_t denote the return
        after t up through T(t). Then {G_t}_{t in T(s)} are the returns that pertain to state s, and
        {rho t:T(t)-1|}_{t in T(s)} are the corresponding importance-sampling ratios. To estimate v_pi(s),
        we simply scale the returns by the ratios and average the results.

        Every visit method.
        Need: Trajectories.
        Generate rho on the fly:
            product [k=t to T-1] pi(A_k|S_k)/mu(A_k|S_k)

        V(s) = sum [t in Tee(s)] rho_t:T(t)-1 G_t / |Tee(s)|
        """
        value_estimates: dict[BlackJackObsT, float] = defaultdict(float)
        denom: dict[BlackJackObsT, float] = defaultdict(float)

        result = {obs: [] for obs in eval_states}

        for idx, trajectory in enumerate(mu_trajectories, start=1):
            ratio = 1
            G = 0
            for (obs, act, reward) in trajectory[::-1]:
                ratio *= self.pi[obs][act] / mu_policy[obs][act]
                G = G * self.gamma + reward

                if obs in eval_states:
                    denom[obs] += ratio
                    value_estimates[obs] += G * ratio

            if idx in checkpoints:
                for obs in eval_states:
                    if denom[obs] > 0:
                        result[obs].append(value_estimates[obs] / denom[obs])
                    else:
                        result[obs].append(0.0)

        return result

def one_run(
        behavioural_agent: ImportanceSampling_BlackjackAgent,
        target_agent: ImportanceSampling_BlackjackAgent,
        episodes: int,
        checkpoints: list,
        eval_states: list[BlackJackObsT],
) -> tuple[dict[BlackJackObsT, list[float]], dict[BlackJackObsT, list[float]]]:
    mu_episodes = []
    for _ in range(episodes):
        mu_episodes.append(behavioural_agent.generate_episode())

    result1 = target_agent.ordinary_IS(
        mu_episodes,
        behavioural_agent.pi,
        # checkpoints=list(range(1, episodes + 1)),
        checkpoints=checkpoints,
        eval_states=eval_states
    )

    result2 = target_agent.weighted_IS(
                mu_episodes,
                behavioural_agent.pi,
                # checkpoints=list(range(1, episodes + 1)),
                checkpoints=checkpoints,
                eval_states=eval_states
            )

    return result1, result2


def plot_results(series1: list[list[float]],
                 series2: list[list[float]],
                 state: BlackJackObsT,
                 /, *,
                 runs: int,
                 length: int,
                 truth: float | None,
                 error: bool,
                 checkpoints: list[int],
                 plot_std: bool,
                 ylim: tuple[float, float]=(0, 5),
) -> Figure:
    figure = plt.figure(figsize=(12, 6))
    axes = plt.gca()

    if error:
        np_series1 = (np.array(series1) - truth) ** 2
        np_series2 = (np.array(series2) - truth) ** 2
        y_label = f"Mean\nSquared\nError\n\n(average\nover\n{runs:,} runs)"
    else:
        np_series1 = np.array(series1)
        np_series2 = np.array(series2)
        y_label = f"Mean\nEstimate\n\n(average\nover\n{runs:,} runs)"

    ordinary_mean = np_series1.mean(axis=0)
    ordinary_std = np_series1.std(axis=0)
    weighted_mean = np_series2.mean(axis=0)
    weighted_std = np_series2.std(axis=0)

    axes.plot(checkpoints, ordinary_mean, color="lime", label=f"Ordinary IS obs={state}")
    axes.plot(checkpoints, weighted_mean, color="red", label=f"Weighted IS obs={state}")

    if not error and truth is not None:
        axes.axhline(truth, color="black", linestyle="--", label=f"True value obs={state}", zorder=0, linewidth=1)

    if plot_std:
        axes.fill_between(
            checkpoints,
            ordinary_mean - ordinary_std,
            ordinary_mean + ordinary_std,
            color="lime",
            alpha=0.2,
        )

        axes.fill_between(
            checkpoints,
            weighted_mean - weighted_std,
            weighted_mean + weighted_std,
            color="red",
            alpha=0.2,
        )

    axes.set_xscale("log")
    tick_values = [10**power for power in range(0, int(math.log10(length)) + 1)]
    tick_labels = [str(value) for value in tick_values[:]]

    axes.set_xticks(tick_values)
    axes.set_xticklabels(tick_labels)
    axes.tick_params(axis="both", which="major", direction="in")
    axes.minorticks_off()

    axes.set_xlim(0.9, length)
    axes.set_ylim(*ylim)
    axes.legend()

    axes.set_xlabel("Episodes (log scale)", fontsize=12)
    axes.set_ylabel(y_label, rotation=0, fontsize=12, labelpad=50, va="center")
    axes.set_title("Ordinary vs Weighted Importance Sampling", fontsize=14, pad=10)

    figure.tight_layout()
    return figure

def _run_chunk(
        args: tuple[float, int, list[int], list[BlackJackObsT], list[int]]
) -> tuple[dict[BlackJackObsT, list[list[float]]], dict[BlackJackObsT, list[list[float]]]]:
    hit, episodes, checkpoints, eval_states, seeds = args
    stick = 1 - hit

    chunk_results1: dict[BlackJackObsT, list[list[float]]] = defaultdict(list)
    chunk_results2: dict[BlackJackObsT, list[list[float]]] = defaultdict(list)

    mu = ImportanceSampling_BlackjackAgent.make_universal_policy(hit=hit, stick=stick)
    bj = cast(BlackjackEnv, gym.make("Blackjack-v1", sab=True).unwrapped)
    behavioural_agent = ImportanceSampling_BlackjackAgent(bj, gamma=1.0, pi=mu, fixed_pi=True)

    target_agent_policy = MC_ES_BlackjackAgent.make_sab_policy()
    target_agent = ImportanceSampling_BlackjackAgent(bj, gamma=1.0, pi=target_agent_policy, fixed_pi=True)

    for seed in seeds:
        bj.reset(seed=seed)
        result1, result2 = one_run(behavioural_agent, target_agent,episodes, checkpoints, eval_states)
        for obs, estimates in result1.items():
            chunk_results1[obs].append(estimates)
        for obs, estimates in result2.items():
            chunk_results2[obs].append(estimates)

    return chunk_results1, chunk_results2

if __name__ == "__main__":
    import sys
    length = int(sys.argv[1])
    runs = int(sys.argv[2])

    hit = float(sys.argv[3]) if len(sys.argv) > 3 else 0.5
    stick = 1 - hit
    print(f"Using behaviour policy with hit probability {hit:.2f} and stick probability {stick:.2f}")

    WORKERS = 8
    CHUNK_SIZE = runs // (WORKERS * 8)

    STATE = (13, 2, True)
    TRUTH = -0.27726
    SAMPLES_PER_DECADE = 10
    num_decades = math.log10(length)
    num_points = int(num_decades * SAMPLES_PER_DECADE) + 1

    CHECKPOINTS = np.logspace(
        0,
        math.log10(length),
        num=num_points,
    )
    CHECKPOINTS = np.unique(np.rint(CHECKPOINTS).astype(int))
    CHECKPOINTS[0] = 1
    CHECKPOINTS[-1] = length
    CHECKPOINTS = CHECKPOINTS.tolist()
    print(CHECKPOINTS)

    PLOT_STD = True

    results1: dict[BlackJackObsT, list[list[float]]] = defaultdict(list)
    results2: dict[BlackJackObsT, list[list[float]]] = defaultdict(list)
    base_seed = 0
    run_seeds = [base_seed + run_idx for run_idx in range(runs)]
    chunk_args = [
        (hit, length, CHECKPOINTS, [STATE], run_seeds[start:start + CHUNK_SIZE])
        for start in range(0, runs, CHUNK_SIZE)
    ]
    with ProcessPoolExecutor(max_workers=WORKERS, mp_context=mp.get_context("spawn")) as executor:
        for chunk_results in tqdm(executor.map(_run_chunk, chunk_args), total=len(chunk_args), desc="Run chunks", position=0):
            for obs, estimates in chunk_results[0].items():
                results1[obs].extend(estimates)
            for obs, estimates in chunk_results[1].items():
                results2[obs].extend(estimates)

    figure = plot_results(results1[STATE], results2[STATE], STATE,
                          runs=runs, length=length,
                          checkpoints=CHECKPOINTS, plot_std=PLOT_STD,
                          truth=TRUTH, error=True)

    hitstring = f"_hit{hit:.2f}" if hit != 0.5 else ""
    figure.savefig(f"model_free/blackjack/importance_sampling_l{length}_r{runs}{hitstring}.png")

    figure2 = plot_results(results1[STATE], results2[STATE], STATE,
                           runs=runs, length=length,
                           checkpoints=CHECKPOINTS, plot_std=PLOT_STD,
                           truth=TRUTH, error=False, ylim=(-2, 2))
    figure2.savefig(f"model_free/blackjack/importance_sampling_estimates_l{length}_r{runs}{hitstring}.png")

    # total_reward = 0.0
    # for i in tqdm(range(100_000)):
    #     episode = target_agent.generate_episode()
    #     total_reward += episode[-1][2]
    # print(total_reward / 100_000)
